// Generated by @naeemo/capnp
// DO NOT EDIT MANUALLY

import { MessageReader, MessageBuilder, StructReader, StructBuilder, createUnionReader, createUnionBuilder } from "@naeemo/capnp";

// XOR helpers for default value encoding
function xorFloat32(a: number, b: number): number {
  const view = new DataView(new ArrayBuffer(4));
  view.setFloat32(0, a, true);
  const aBits = view.getUint32(0, true);
  view.setFloat32(0, b, true);
  const bBits = view.getUint32(0, true);
  view.setUint32(0, aBits ^ bBits, true);
  return view.getFloat32(0, true);
}

function xorFloat64(a: number, b: number): number {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, a, true);
  const aBits = view.getBigUint64(0, true);
  view.setFloat64(0, b, true);
  const bBits = view.getBigUint64(0, true);
  view.setBigUint64(0, aBits ^ bBits, true);
  return view.getFloat64(0, true);
}

export interface Expression {
  literal: number;
}

export class ExpressionReader {
  constructor(private reader: StructReader) {}

  get literal(): number { return xorFloat64(this.reader.getFloat64(0), 0); }

}

export class ExpressionBuilder {
  constructor(private builder: StructBuilder) {}

  setLiteral(value: number): void { this.builder.setFloat64(0, xorFloat64(value, 0)); }

}

export interface EvaluateParams {
  // Note: Could not parse struct fields
}

export class EvaluateParamsReader {
  constructor(private reader: StructReader) {}
}

export class EvaluateParamsBuilder {
  constructor(private builder: StructBuilder) {}
}

export interface EvaluateResults {
  value: number;
}

export class EvaluateResultsReader {
  constructor(private reader: StructReader) {}

  get value(): number { return xorFloat64(this.reader.getFloat64(0), 0); }

}

export class EvaluateResultsBuilder {
  constructor(private builder: StructBuilder) {}

  setValue(value: number): void { this.builder.setFloat64(0, xorFloat64(value, 0)); }

}

export enum Operator {
  add = 0,
  subtract = 1,
  multiply = 2,
  divide = 3,
}

export interface GetOperatorParams {
  op: Operator;
}

export class GetOperatorParamsReader {
  constructor(private reader: StructReader) {}

  get op(): unknown { return this.reader.getEnum(0) ^ 0; }

}

export class GetOperatorParamsBuilder {
  constructor(private builder: StructBuilder) {}

  setOp(value: unknown): void { this.builder.setEnum(0, value ^ 0); }

}

export interface Function {
  interfaceId: bigint;
  methodId: number;
}

export class FunctionReader {
  constructor(private reader: StructReader) {}

  get interfaceId(): bigint { return this.reader.getUint64(0) ^ 0n; }

  get methodId(): number { return this.reader.getUint16(8) ^ 0; }

}

export class FunctionBuilder {
  constructor(private builder: StructBuilder) {}

  setInterfaceId(value: bigint): void { this.builder.setUint64(0, value ^ 0n); }

  setMethodId(value: number): void { this.builder.setUint16(8, value ^ 0); }

}

export interface GetOperatorResults {
  func: Function;
}

export class GetOperatorResultsReader {
  constructor(private reader: StructReader) {}

  get func(): unknown { return undefined; }

}

export class GetOperatorResultsBuilder {
  constructor(private builder: StructBuilder) {}

  setFunc(value: unknown): void { /* TODO */ }

}

// Calculator Method IDs
export const CalculatorInterfaceId = 10116611291049685529n;
export const CalculatorMethodIds = {
  evaluate: 0,
  getOperator: 1,
} as const;

// Calculator Server Interface
export interface CalculatorServer {
  evaluate(context: CallContext<EvaluateParams, EvaluateResults>): Promise<void>;
  getOperator(context: CallContext<GetOperatorParams, GetOperatorResults>): Promise<void>;
}

// Calculator Client Class
export class CalculatorClient extends BaseCapabilityClient {
  static readonly interfaceId = 10116611291049685529n;

  /**
   * evaluate
   * @param params - EvaluateParams
   * @returns PipelineClient<EvaluateResults>
   */
  evaluate(params: EvaluateParams): PipelineClient<EvaluateResults> {
    return this._call(
      CalculatorClient.interfaceId,
      CalculatorMethodIds.evaluate,
      params
    ) as PipelineClient<EvaluateResults>;
  }

  /**
   * getOperator
   * @param params - GetOperatorParams
   * @returns PipelineClient<GetOperatorResults>
   */
  getOperator(params: GetOperatorParams): PipelineClient<GetOperatorResults> {
    return this._call(
      CalculatorClient.interfaceId,
      CalculatorMethodIds.getOperator,
      params
    ) as PipelineClient<GetOperatorResults>;
  }

}
