// Generated by capnp-ts-codegen
import { StructReader, StructBuilder, MessageReader, MessageBuilder, ElementSize } from '@capnp-ts/core';

export class Person_Reader extends StructReader {

  get id(): number {
    return this.getUint32(0);
  }

  get name(): string {
    return this.getText(0);
  }

  get email(): string {
    return this.getText(1);
  }
}

export class Person_Builder extends StructBuilder {

  set id(value: number) {
    this.setUint32(0, value);
  }

  set name(value: string) {
    this.setText(0, value);
  }

  set email(value: string) {
    this.setText(1, value);
  }
}

export class AddressBook_Reader extends StructReader {
}

export class AddressBook_Builder extends StructBuilder {
}
