/**
 * 基于 Binary Schema 的 TypeScript 代码生成器
 * 
 * 使用官方 capnp 编译器生成的二进制 schema 来生成 TypeScript 代码
 */

import type { 
  CodeGeneratorRequestReader, 
  NodeReader, 
  FieldReader, 
  TypeReader,
  TypeKind,
  Id 
} from '../schema/schema-reader.js';

// 导入运行时类型用于代码生成
import type { StructReader, StructBuilder } from '../core/index.js';

export interface GeneratorOptions {
  /** 运行时库导入路径 */
  runtimeImportPath?: string;
}

const DEFAULT_OPTIONS: GeneratorOptions = {
  runtimeImportPath: '@naeemo/capnp',
};

/**
 * 从 CodeGeneratorRequest 生成 TypeScript 代码
 */
export function generateFromRequest(
  request: CodeGeneratorRequestReader,
  options?: GeneratorOptions
): Map<string, string> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const files = new Map<string, string>();
  
  const nodes = request.nodes;
  const requestedFiles = request.requestedFiles;
  
  // 为每个请求的文件生成代码
  for (const file of requestedFiles) {
    const filename = file.filename.replace(/\.capnp$/, '.ts');
    const code = generateFile(file.id, nodes, opts);
    files.set(filename, code);
  }
  
  return files;
}

/**
 * 生成单个文件的 TypeScript 代码
 */
function generateFile(
  fileId: Id,
  allNodes: NodeReader[],
  options: GeneratorOptions
): string {
  const lines: string[] = [];
  
  // 文件头
  lines.push('// Generated by @naeemo/capnp');
  lines.push('// DO NOT EDIT MANUALLY');
  lines.push('');
  lines.push(`import { MessageReader, MessageBuilder, StructReader, StructBuilder } from "${options.runtimeImportPath}";`);
  lines.push('');
  
  // 找到属于这个文件的所有节点
  const fileNodes = allNodes.filter(n => n.scopeId === fileId);
  
  // 生成每个节点的代码
  for (const node of fileNodes) {
    if (node.isStruct) {
      lines.push(generateStruct(node, allNodes));
    } else if (node.isEnum) {
      lines.push(generateEnum(node));
    }
    lines.push('');
  }
  
  return lines.join('\n');
}

/**
 * 生成 Struct 的 TypeScript 代码
 */
function generateStruct(node: NodeReader, allNodes: NodeReader[]): string {
  const lines: string[] = [];
  const structName = getShortName(node.displayName);
  
  // 生成接口定义
  lines.push(`export interface ${structName} {`);
  for (const field of node.structFields) {
    const tsType = getTypeScriptType(field.slotType, allNodes);
    lines.push(`  ${field.name}: ${tsType};`);
  }
  lines.push('}');
  lines.push('');
  
  // 生成 Reader 类
  lines.push(`export class ${structName}Reader {`);
  lines.push(`  constructor(private reader: StructReader) {}`);
  lines.push('');
  
  for (const field of node.structFields) {
    if (!field.isSlot) continue; // Skip group fields for now
    
    const getter = generateFieldGetter(field);
    lines.push(`  ${getter}`);
    lines.push('');
  }
  
  lines.push('}');
  lines.push('');
  
  // 生成 Builder 类
  lines.push(`export class ${structName}Builder {`);
  lines.push(`  constructor(private builder: StructBuilder) {}`);
  lines.push('');
  
  for (const field of node.structFields) {
    if (!field.isSlot) continue; // Skip group fields for now
    
    const setter = generateFieldSetter(field);
    lines.push(`  ${setter}`);
    lines.push('');
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

/**
 * 生成字段 getter
 */
function generateFieldGetter(field: FieldReader): string {
  const name = field.name;
  const type = field.slotType;
  
  if (!type) {
    return `get ${name}(): unknown { return undefined; }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `get ${name}(): void { return undefined; }`;
    case 'bool':
      return `get ${name}(): boolean { return this.reader.getBool(${field.slotOffset * 8}); }`;
    case 'int8':
      return `get ${name}(): number { return this.reader.getInt8(${field.slotOffset}); }`;
    case 'int16':
      return `get ${name}(): number { return this.reader.getInt16(${field.slotOffset * 2}); }`;
    case 'int32':
      return `get ${name}(): number { return this.reader.getInt32(${field.slotOffset * 4}); }`;
    case 'int64':
      return `get ${name}(): bigint { return this.reader.getInt64(${field.slotOffset * 8}); }`;
    case 'uint8':
      return `get ${name}(): number { return this.reader.getUint8(${field.slotOffset}); }`;
    case 'uint16':
      return `get ${name}(): number { return this.reader.getUint16(${field.slotOffset * 2}); }`;
    case 'uint32':
      return `get ${name}(): number { return this.reader.getUint32(${field.slotOffset * 4}); }`;
    case 'uint64':
      return `get ${name}(): bigint { return this.reader.getUint64(${field.slotOffset * 8}); }`;
    case 'float32':
      return `get ${name}(): number { return this.reader.getFloat32(${field.slotOffset * 4}); }`;
    case 'float64':
      return `get ${name}(): number { return this.reader.getFloat64(${field.slotOffset * 8}); }`;
    case 'text':
      return `get ${name}(): string { return this.reader.getText(${field.slotOffset}); }`;
    case 'data':
      return `get ${name}(): Uint8Array { return this.reader.getData(${field.slotOffset}); }`;
    default:
      return `get ${name}(): unknown { return undefined; }`;
  }
}

/**
 * 生成字段 setter
 */
function generateFieldSetter(field: FieldReader): string {
  const name = field.name;
  const type = field.slotType;
  const paramType = getTypeScriptTypeForSetter(type);
  
  if (!type) {
    return `set${capitalize(name)}(value: unknown): void { /* TODO */ }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `set${capitalize(name)}(value: void): void { /* void */ }`;
    case 'bool':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setBool(${field.slotOffset * 8}, value); }`;
    case 'int8':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt8(${field.slotOffset}, value); }`;
    case 'int16':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt16(${field.slotOffset * 2}, value); }`;
    case 'int32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt32(${field.slotOffset * 4}, value); }`;
    case 'int64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt64(${field.slotOffset * 8}, value); }`;
    case 'uint8':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint8(${field.slotOffset}, value); }`;
    case 'uint16':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint16(${field.slotOffset * 2}, value); }`;
    case 'uint32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint32(${field.slotOffset * 4}, value); }`;
    case 'uint64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint64(${field.slotOffset * 8}, value); }`;
    case 'float32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat32(${field.slotOffset * 4}, value); }`;
    case 'float64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat64(${field.slotOffset * 8}, value); }`;
    case 'text':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setText(${field.slotOffset}, value); }`;
    case 'data':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setData(${field.slotOffset}, value); }`;
    default:
      return `set${capitalize(name)}(value: ${paramType}): void { /* TODO */ }`;
  }
}

/**
 * 获取 TypeScript setter 参数类型
 */
function getTypeScriptTypeForSetter(type: TypeReader | null): string {
  if (!type) return 'unknown';
  
  switch (type.kind) {
    case 'void': return 'void';
    case 'bool': return 'boolean';
    case 'int8':
    case 'int16':
    case 'int32':
    case 'uint8':
    case 'uint16':
    case 'uint32':
    case 'float32':
    case 'float64':
      return 'number';
    case 'int64':
    case 'uint64':
      return 'bigint';
    case 'text': return 'string';
    case 'data': return 'Uint8Array';
    default:
      return 'unknown';
  }
}

/**
 * 首字母大写
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * 生成 Enum 的 TypeScript 代码
 */
function generateEnum(node: NodeReader): string {
  const lines: string[] = [];
  const enumName = getShortName(node.displayName);
  
  lines.push(`export enum ${enumName} {`);
  for (const enumerant of node.enumEnumerants) {
    lines.push(`  ${enumerant.name} = ${enumerant.codeOrder},`);
  }
  lines.push('}');
  
  return lines.join('\n');
}

/**
 * 获取 TypeScript 类型字符串
 */
function getTypeScriptType(type: TypeReader | null, allNodes: NodeReader[]): string {
  if (!type) return 'unknown';
  
  switch (type.kind) {
    case 'void': return 'void';
    case 'bool': return 'boolean';
    case 'int8':
    case 'int16':
    case 'int32':
    case 'uint8':
    case 'uint16':
    case 'uint32':
    case 'float32':
    case 'float64':
      return 'number';
    case 'int64':
    case 'uint64':
      return 'bigint';
    case 'text': return 'string';
    case 'data': return 'Uint8Array';
    case 'list': {
      const elementType = type.listElementType;
      if (!elementType) return 'unknown[]';
      const elemTsType = getTypeScriptType(elementType, allNodes);
      return `${elemTsType}[]`;
    }
    case 'struct': {
      const structNode = allNodes.find(n => n.id === type.typeId);
      if (structNode) {
        return getShortName(structNode.displayName);
      }
      return 'unknown';
    }
    case 'enum': {
      const enumNode = allNodes.find(n => n.id === type.typeId);
      if (enumNode) {
        return getShortName(enumNode.displayName);
      }
      return 'unknown';
    }
    default:
      return 'unknown';
  }
}

/**
 * 从 displayName 获取短名称
 * 例如 "test-schema.capnp:Person" -> "Person"
 */
function getShortName(displayName: string): string {
  const colonIndex = displayName.lastIndexOf(':');
  if (colonIndex >= 0) {
    return displayName.substring(colonIndex + 1);
  }
  // 如果没有冒号，可能是文件名，返回空或文件名
  return displayName.replace(/\.capnp$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
}
