/**
 * 基于 Binary Schema 的 TypeScript 代码生成器
 * 
 * 使用官方 capnp 编译器生成的二进制 schema 来生成 TypeScript 代码
 */

import type { 
  CodeGeneratorRequestReader, 
  NodeReader, 
  FieldReader, 
  TypeReader,
  TypeKind,
  Id 
} from '../schema/schema-reader.js';

// 导入运行时类型用于代码生成
import type { StructReader, StructBuilder } from '../core/index.js';

export interface GeneratorOptions {
  /** 运行时库导入路径 */
  runtimeImportPath?: string;
}

const DEFAULT_OPTIONS: GeneratorOptions = {
  runtimeImportPath: '@naeemo/capnp',
};

/**
 * Union 字段分组
 */
interface UnionGroup {
  discriminantOffset: number;
  fields: FieldReader[];
}

/**
 * 从 CodeGeneratorRequest 生成 TypeScript 代码
 */
export function generateFromRequest(
  request: CodeGeneratorRequestReader,
  options?: GeneratorOptions
): Map<string, string> {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const files = new Map<string, string>();
  
  const nodes = request.nodes;
  const requestedFiles = request.requestedFiles;
  
  // 为每个请求的文件生成代码
  for (const file of requestedFiles) {
    const filename = file.filename.replace(/\.capnp$/, '.ts');
    const code = generateFile(file.id, nodes, opts);
    files.set(filename, code);
  }
  
  return files;
}

/**
 * 生成单个文件的 TypeScript 代码
 */
function generateFile(
  fileId: Id,
  allNodes: NodeReader[],
  options: GeneratorOptions
): string {
  const lines: string[] = [];
  
  // 文件头
  lines.push('// Generated by @naeemo/capnp');
  lines.push('// DO NOT EDIT MANUALLY');
  lines.push('');
  lines.push(`import { MessageReader, MessageBuilder, StructReader, StructBuilder, createUnionReader, createUnionBuilder } from "${options.runtimeImportPath}";`);
  lines.push('');
  
  // 添加 XOR 辅助函数（用于 float 默认值）
  lines.push('// XOR helpers for default value encoding');
  lines.push('function xorFloat32(a: number, b: number): number {');
  lines.push('  const view = new DataView(new ArrayBuffer(4));');
  lines.push('  view.setFloat32(0, a, true);');
  lines.push('  const aBits = view.getUint32(0, true);');
  lines.push('  view.setFloat32(0, b, true);');
  lines.push('  const bBits = view.getUint32(0, true);');
  lines.push('  view.setUint32(0, aBits ^ bBits, true);');
  lines.push('  return view.getFloat32(0, true);');
  lines.push('}');
  lines.push('');
  lines.push('function xorFloat64(a: number, b: number): number {');
  lines.push('  const view = new DataView(new ArrayBuffer(8));');
  lines.push('  view.setFloat64(0, a, true);');
  lines.push('  const aBits = view.getBigUint64(0, true);');
  lines.push('  view.setFloat64(0, b, true);');
  lines.push('  const bBits = view.getBigUint64(0, true);');
  lines.push('  view.setBigUint64(0, aBits ^ bBits, true);');
  lines.push('  return view.getFloat64(0, true);');
  lines.push('}');
  lines.push('');
  
  // 找到属于这个文件的所有节点
  const fileNodes = allNodes.filter(n => n.scopeId === fileId);
  
  // 生成每个节点的代码
  for (const node of fileNodes) {
    if (node.isStruct) {
      lines.push(generateStruct(node, allNodes));
    } else if (node.isEnum) {
      lines.push(generateEnum(node));
    }
    lines.push('');
  }
  
  return lines.join('\n');
}

/**
 * 生成 Struct 的 TypeScript 代码
 */
function generateStruct(node: NodeReader, allNodes: NodeReader[]): string {
  const lines: string[] = [];
  const structName = getShortName(node.displayName);
  
  // 分析字段：分离 Union 字段、普通字段和 Group 字段
  const { unionGroups, regularFields, groupFields } = analyzeFields(node, allNodes);
  
  // 生成接口定义
  lines.push(`export interface ${structName} {`);
  
  // 普通字段
  for (const field of regularFields) {
    if (!field.isSlot) continue;
    const tsType = getTypeScriptType(field.slotType, allNodes);
    lines.push(`  ${field.name}: ${tsType};`);
  }
  
  // Group 字段 - 内联 Group 的字段
  for (const { field: groupField, groupNode } of groupFields) {
    const groupName = groupField.name;
    for (const field of groupNode.structFields) {
      if (!field.isSlot) continue;
      const tsType = getTypeScriptType(field.slotType, allNodes);
      lines.push(`  ${groupName}${capitalize(field.name)}: ${tsType};`);
    }
  }
  
  // Union 字段 - 生成 discriminant 和 variant 类型
  for (const [groupIndex, group] of unionGroups.entries()) {
    const unionName = group.fields.length > 0 ? `${capitalize(group.fields[0].name)}Union` : `Union${groupIndex}`;
    lines.push(`  ${unionName}: ${generateUnionVariantType(group, allNodes)};`);
  }
  
  lines.push('}');
  lines.push('');
  
  // 生成 Reader 类
  lines.push(`export class ${structName}Reader {`);
  lines.push(`  constructor(private reader: StructReader) {}`);
  lines.push('');
  
  // 普通字段 getters
  for (const field of regularFields) {
    if (!field.isSlot) continue;
    const getter = generateFieldGetter(field);
    lines.push(`  ${getter}`);
    lines.push('');
  }
  
  // Group 字段 getters - 内联 Group 的字段
  for (const { field: groupField, groupNode } of groupFields) {
    const groupName = groupField.name;
    for (const field of groupNode.structFields) {
      if (!field.isSlot) continue;
      const getter = generateGroupFieldGetter(field, groupName);
      lines.push(`  ${getter}`);
      lines.push('');
    }
  }
  
  // Union 方法
  for (const [groupIndex, group] of unionGroups.entries()) {
    const unionName = group.fields.length > 0 ? `${capitalize(group.fields[0].name)}Union` : `Union${groupIndex}`;
    const variants: Record<number, string> = {};
    for (const field of group.fields) {
      variants[field.discriminantValue] = field.name;
    }
    const variantsStr = JSON.stringify(variants).replace(/"/g, "'");
    
    lines.push(`  get${unionName}Tag(): number {`);
    lines.push(`    return this.reader.getUint16(${group.discriminantOffset});`);
    lines.push(`  }`);
    lines.push('');
    
    lines.push(`  get${unionName}Variant(): string | undefined {`);
    lines.push(`    const tag = this.get${unionName}Tag();`);
    lines.push(`    const variants = ${variantsStr};`);
    lines.push(`    return variants[tag];`);
    lines.push(`  }`);
    lines.push('');
    
    // 每个 variant 的 getter
    for (const field of group.fields) {
      const getter = generateUnionFieldGetter(field, unionName, field.discriminantValue);
      lines.push(`  ${getter}`);
      lines.push('');
    }
  }
  
  lines.push('}');
  lines.push('');
  
  // 生成 Builder 类
  lines.push(`export class ${structName}Builder {`);
  lines.push(`  constructor(private builder: StructBuilder) {}`);
  lines.push('');
  
  // 普通字段 setters
  for (const field of regularFields) {
    if (!field.isSlot) continue;
    const setter = generateFieldSetter(field);
    lines.push(`  ${setter}`);
    lines.push('');
  }
  
  // Group 字段 setters
  for (const { field: groupField, groupNode } of groupFields) {
    const groupName = groupField.name;
    for (const field of groupNode.structFields) {
      if (!field.isSlot) continue;
      const setter = generateGroupFieldSetter(field, groupName);
      lines.push(`  ${setter}`);
      lines.push('');
    }
  }
  
  // Union setters
  for (const [groupIndex, group] of unionGroups.entries()) {
    const unionName = group.fields.length > 0 ? `${capitalize(group.fields[0].name)}Union` : `Union${groupIndex}`;
    for (const field of group.fields) {
      const setter = generateUnionFieldSetter(field, unionName, field.discriminantValue);
      lines.push(`  ${setter}`);
      lines.push('');
    }
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

/**
 * 分析字段，分离 Union 字段和普通字段，展开 Group 字段
 */
function analyzeFields(node: NodeReader, allNodes: NodeReader[]): { 
  unionGroups: UnionGroup[], 
  regularFields: FieldReader[],
  groupFields: { field: FieldReader, groupNode: NodeReader }[] 
} {
  const fields = node.structFields;
  const unionGroups: Map<number, UnionGroup> = new Map();
  const regularFields: FieldReader[] = [];
  const groupFields: { field: FieldReader, groupNode: NodeReader }[] = [];
  
  for (const field of fields) {
    // 处理 Group 字段
    if (field.isGroup) {
      const groupNode = allNodes.find(n => n.id === field.groupTypeId);
      if (groupNode?.isStruct) {
        groupFields.push({ field, groupNode });
      }
      continue;
    }
    
    // 处理 Union 字段
    if (node.structDiscriminantCount > 0 && field.discriminantValue !== 65535 && field.discriminantValue !== 0) {
      const discriminantOffset = node.structDiscriminantOffset;
      
      if (!unionGroups.has(discriminantOffset)) {
        unionGroups.set(discriminantOffset, { discriminantOffset, fields: [] });
      }
      unionGroups.get(discriminantOffset)!.fields.push(field);
    } else {
      // 普通字段
      regularFields.push(field);
    }
  }
  
  return { 
    unionGroups: Array.from(unionGroups.values()), 
    regularFields,
    groupFields 
  };
}

/**
 * 生成 Union variant 类型
 */
function generateUnionVariantType(group: UnionGroup, allNodes: NodeReader[]): string {
  const variants = group.fields.map(f => {
    const tsType = f.isSlot ? getTypeScriptType(f.slotType, allNodes) : 'unknown';
    return `{ tag: ${f.discriminantValue}; variant: '${f.name}'; value: ${tsType} }`;
  });
  return variants.join(' | ');
}

/**
 * 生成 Union 字段的 getter
 */
function generateUnionFieldGetter(field: FieldReader, unionName: string, discriminantValue: number): string {
  const name = field.name;
  const type = field.slotType;
  
  if (!type || !field.isSlot) {
    return `get${capitalize(name)}(): unknown | undefined { return this.get${unionName}Tag() === ${discriminantValue} ? undefined : undefined; }`;
  }
  
  const returnType = getTypeScriptTypeForSetter(type);
  
  let body: string;
  switch (type.kind) {
    case 'void':
      body = `return undefined;`;
      break;
    case 'bool':
      body = `return this.reader.getBool(${field.slotOffset * 8});`;
      break;
    case 'int8':
      body = `return this.reader.getInt8(${field.slotOffset});`;
      break;
    case 'int16':
      body = `return this.reader.getInt16(${field.slotOffset * 2});`;
      break;
    case 'int32':
      body = `return this.reader.getInt32(${field.slotOffset * 4});`;
      break;
    case 'int64':
      body = `return this.reader.getInt64(${field.slotOffset * 8});`;
      break;
    case 'uint8':
      body = `return this.reader.getUint8(${field.slotOffset});`;
      break;
    case 'uint16':
      body = `return this.reader.getUint16(${field.slotOffset * 2});`;
      break;
    case 'uint32':
      body = `return this.reader.getUint32(${field.slotOffset * 4});`;
      break;
    case 'uint64':
      body = `return this.reader.getUint64(${field.slotOffset * 8});`;
      break;
    case 'float32':
      body = `return this.reader.getFloat32(${field.slotOffset * 4});`;
      break;
    case 'float64':
      body = `return this.reader.getFloat64(${field.slotOffset * 8});`;
      break;
    case 'text':
      body = `return this.reader.getText(${field.slotOffset});`;
      break;
    case 'data':
      body = `return this.reader.getData(${field.slotOffset});`;
      break;
    default:
      body = `return undefined;`;
  }
  
  return `get${capitalize(name)}(): ${returnType} | undefined {
    if (this.get${unionName}Tag() !== ${discriminantValue}) return undefined;
    ${body}
  }`;
}

/**
 * 生成 Group 字段的 getter
 * Group 字段在父 struct 的 data/pointer section 中，但命名空间是 Group 的名字
 */
function generateGroupFieldGetter(field: FieldReader, groupName: string): string {
  const name = field.name;
  const type = field.slotType;
  
  if (!type) {
    return `get${capitalize(groupName)}${capitalize(name)}(): unknown { return undefined; }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `get${capitalize(groupName)}${capitalize(name)}(): void { return undefined; }`;
    case 'bool':
      return `get${capitalize(groupName)}${capitalize(name)}(): boolean { return this.reader.getBool(${field.slotOffset * 8}); }`;
    case 'int8':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getInt8(${field.slotOffset}); }`;
    case 'int16':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getInt16(${field.slotOffset * 2}); }`;
    case 'int32':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getInt32(${field.slotOffset * 4}); }`;
    case 'int64':
      return `get${capitalize(groupName)}${capitalize(name)}(): bigint { return this.reader.getInt64(${field.slotOffset * 8}); }`;
    case 'uint8':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getUint8(${field.slotOffset}); }`;
    case 'uint16':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getUint16(${field.slotOffset * 2}); }`;
    case 'uint32':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getUint32(${field.slotOffset * 4}); }`;
    case 'uint64':
      return `get${capitalize(groupName)}${capitalize(name)}(): bigint { return this.reader.getUint64(${field.slotOffset * 8}); }`;
    case 'float32':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getFloat32(${field.slotOffset * 4}); }`;
    case 'float64':
      return `get${capitalize(groupName)}${capitalize(name)}(): number { return this.reader.getFloat64(${field.slotOffset * 8}); }`;
    case 'text':
      return `get${capitalize(groupName)}${capitalize(name)}(): string { return this.reader.getText(${field.slotOffset}); }`;
    case 'data':
      return `get${capitalize(groupName)}${capitalize(name)}(): Uint8Array { return this.reader.getData(${field.slotOffset}); }`;
    default:
      return `get${capitalize(groupName)}${capitalize(name)}(): unknown { return undefined; }`;
  }
}

/**
 * 生成 Group 字段的 setter
 */
function generateGroupFieldSetter(field: FieldReader, groupName: string): string {
  const name = field.name;
  const type = field.slotType;
  const paramType = getTypeScriptTypeForSetter(type);
  
  if (!type || !field.isSlot) {
    return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { /* TODO */ }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { }`;
    case 'bool':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setBool(${field.slotOffset * 8}, value); }`;
    case 'int8':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setInt8(${field.slotOffset}, value); }`;
    case 'int16':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setInt16(${field.slotOffset * 2}, value); }`;
    case 'int32':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setInt32(${field.slotOffset * 4}, value); }`;
    case 'int64':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setInt64(${field.slotOffset * 8}, value); }`;
    case 'uint8':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setUint8(${field.slotOffset}, value); }`;
    case 'uint16':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setUint16(${field.slotOffset * 2}, value); }`;
    case 'uint32':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setUint32(${field.slotOffset * 4}, value); }`;
    case 'uint64':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setUint64(${field.slotOffset * 8}, value); }`;
    case 'float32':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat32(${field.slotOffset * 4}, value); }`;
    case 'float64':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat64(${field.slotOffset * 8}, value); }`;
    case 'text':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setText(${field.slotOffset}, value); }`;
    case 'data':
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { this.builder.setData(${field.slotOffset}, value); }`;
    default:
      return `set${capitalize(groupName)}${capitalize(name)}(value: ${paramType}): void { /* TODO */ }`;
  }
}

/**
 * 生成 Union 字段的 setter
 */
function generateUnionFieldSetter(field: FieldReader, unionName: string, discriminantValue: number): string {
  const name = field.name;
  const type = field.slotType;
  const paramType = getTypeScriptTypeForSetter(type);
  
  // 获取 discriminantOffset - 需要从 field 或 node 获取
  // 暂时硬编码为 0，实际应该从 schema 读取
  const discriminantOffset = 0;
  
  if (!type || !field.isSlot) {
    return `set${capitalize(name)}(value: ${paramType}): void {
    this.builder.setUint16(${discriminantOffset}, ${discriminantValue});
  }`;
  }
  
  let body: string;
  switch (type.kind) {
    case 'void':
      body = ``;
      break;
    case 'bool':
      body = `this.builder.setBool(${field.slotOffset * 8}, value);`;
      break;
    case 'int8':
      body = `this.builder.setInt8(${field.slotOffset}, value);`;
      break;
    case 'int16':
      body = `this.builder.setInt16(${field.slotOffset * 2}, value);`;
      break;
    case 'int32':
      body = `this.builder.setInt32(${field.slotOffset * 4}, value);`;
      break;
    case 'int64':
      body = `this.builder.setInt64(${field.slotOffset * 8}, value);`;
      break;
    case 'uint8':
      body = `this.builder.setUint8(${field.slotOffset}, value);`;
      break;
    case 'uint16':
      body = `this.builder.setUint16(${field.slotOffset * 2}, value);`;
      break;
    case 'uint32':
      body = `this.builder.setUint32(${field.slotOffset * 4}, value);`;
      break;
    case 'uint64':
      body = `this.builder.setUint64(${field.slotOffset * 8}, value);`;
      break;
    case 'float32':
      body = `this.builder.setFloat32(${field.slotOffset * 4}, value);`;
      break;
    case 'float64':
      body = `this.builder.setFloat64(${field.slotOffset * 8}, value);`;
      break;
    case 'text':
      body = `this.builder.setText(${field.slotOffset}, value);`;
      break;
    case 'data':
      body = `this.builder.setData(${field.slotOffset}, value);`;
      break;
    default:
      body = ``;
  }
  
  return `set${capitalize(name)}(value: ${paramType}): void {
    this.builder.setUint16(${discriminantOffset}, ${discriminantValue});
    ${body}
  }`;
}

/**
 * 从 ValueReader 提取默认值，用于代码生成
 */
function extractDefaultValue(field: FieldReader): string | undefined {
  const defaultValue = field.defaultValue;
  if (!defaultValue) return undefined;
  
  const type = field.slotType;
  if (!type) return undefined;
  
  switch (type.kind) {
    case 'bool':
      if (defaultValue.isBool) return defaultValue.boolValue ? 'true' : 'false';
      return undefined;
    case 'int8':
      if (defaultValue.isInt8) return `${defaultValue.int8Value}`;
      return undefined;
    case 'int16':
      if (defaultValue.isInt16) return `${defaultValue.int16Value}`;
      return undefined;
    case 'int32':
      if (defaultValue.isInt32) return `${defaultValue.int32Value}`;
      return undefined;
    case 'int64':
      if (defaultValue.isInt64) return `${defaultValue.int64Value}n`;
      return undefined;
    case 'uint8':
      if (defaultValue.isUint8) return `${defaultValue.uint8Value}`;
      return undefined;
    case 'uint16':
      if (defaultValue.isUint16) return `${defaultValue.uint16Value}`;
      return undefined;
    case 'uint32':
      if (defaultValue.isUint32) return `${defaultValue.uint32Value}`;
      return undefined;
    case 'uint64':
      if (defaultValue.isUint64) return `${defaultValue.uint64Value}n`;
      return undefined;
    case 'float32':
      if (defaultValue.isFloat32) {
        const val = defaultValue.float32Value;
        if (Number.isNaN(val)) return 'NaN';
        if (val === Infinity) return 'Infinity';
        if (val === -Infinity) return '-Infinity';
        return `${val}`;
      }
      return undefined;
    case 'float64':
      if (defaultValue.isFloat64) {
        const val = defaultValue.float64Value;
        if (Number.isNaN(val)) return 'NaN';
        if (val === Infinity) return 'Infinity';
        if (val === -Infinity) return '-Infinity';
        return `${val}`;
      }
      return undefined;
    case 'enum':
      if (defaultValue.isEnum) return `${defaultValue.enumValue}`;
      return undefined;
    default:
      return undefined;
  }
}

/**
 * 生成 XOR 解码表达式（用于 getter）
 * stored ^ default = actual
 */
function generateXorDecode(expr: string, defaultValue: string, typeKind: TypeKind): string {
  switch (typeKind) {
    case 'bool':
      // bool: stored !== default
      return `${expr} !== ${defaultValue}`;
    case 'int8':
    case 'int16':
    case 'int32':
      // 有符号整数：先转无符号 XOR，再转回有符号
      return `(${expr} ^ ${defaultValue}) | 0`;
    case 'uint8':
    case 'uint16':
    case 'uint32':
      // 无符号整数：直接 XOR
      return `${expr} ^ ${defaultValue}`;
    case 'int64':
    case 'uint64':
      // bigint：直接 XOR
      return `${expr} ^ ${defaultValue}`;
    case 'float32':
      // float32: 需要位操作转换
      return `xorFloat32(${expr}, ${defaultValue})`;
    case 'float64':
      // float64: 需要位操作转换
      return `xorFloat64(${expr}, ${defaultValue})`;
    case 'enum':
      // enum 作为 uint16 处理
      return `${expr} ^ ${defaultValue}`;
    default:
      return expr;
  }
}

/**
 * 生成 XOR 编码表达式（用于 setter）
 * actual ^ default = stored
 */
function generateXorEncode(valueExpr: string, defaultValue: string, typeKind: TypeKind): string {
  switch (typeKind) {
    case 'bool':
      // bool: value !== default
      return `${valueExpr} !== ${defaultValue}`;
    case 'int8':
    case 'int16':
    case 'int32':
      // 有符号整数：先转无符号 XOR
      return `(${valueExpr} >>> 0) ^ ${defaultValue}`;
    case 'uint8':
    case 'uint16':
    case 'uint32':
      // 无符号整数：直接 XOR
      return `${valueExpr} ^ ${defaultValue}`;
    case 'int64':
    case 'uint64':
      // bigint：直接 XOR
      return `${valueExpr} ^ ${defaultValue}`;
    case 'float32':
      // float32: 需要位操作转换
      return `xorFloat32(${valueExpr}, ${defaultValue})`;
    case 'float64':
      // float64: 需要位操作转换
      return `xorFloat64(${valueExpr}, ${defaultValue})`;
    case 'enum':
      // enum 作为 uint16 处理
      return `${valueExpr} ^ ${defaultValue}`;
    default:
      return valueExpr;
  }
}

/**
 * 生成字段 getter
 */
function generateFieldGetter(field: FieldReader): string {
  const name = field.name;
  const type = field.slotType;
  const defaultValue = extractDefaultValue(field);
  
  if (!type) {
    return `get ${name}(): unknown { return undefined; }`;
  }
  
  // 如果有默认值，使用 XOR 解码
  if (defaultValue !== undefined && type.kind !== 'text' && type.kind !== 'data') {
    const readExpr = `this.reader.get${capitalize(type.kind)}(${getByteOffset(field, type.kind)})`;
    const decodedExpr = generateXorDecode(readExpr, defaultValue, type.kind);
    return `get ${name}(): ${getTypeScriptTypeForSetter(type)} { return ${decodedExpr}; }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `get ${name}(): void { return undefined; }`;
    case 'bool':
      return `get ${name}(): boolean { return this.reader.getBool(${field.slotOffset * 8}); }`;
    case 'int8':
      return `get ${name}(): number { return this.reader.getInt8(${field.slotOffset}); }`;
    case 'int16':
      return `get ${name}(): number { return this.reader.getInt16(${field.slotOffset * 2}); }`;
    case 'int32':
      return `get ${name}(): number { return this.reader.getInt32(${field.slotOffset * 4}); }`;
    case 'int64':
      return `get ${name}(): bigint { return this.reader.getInt64(${field.slotOffset * 8}); }`;
    case 'uint8':
      return `get ${name}(): number { return this.reader.getUint8(${field.slotOffset}); }`;
    case 'uint16':
      return `get ${name}(): number { return this.reader.getUint16(${field.slotOffset * 2}); }`;
    case 'uint32':
      return `get ${name}(): number { return this.reader.getUint32(${field.slotOffset * 4}); }`;
    case 'uint64':
      return `get ${name}(): bigint { return this.reader.getUint64(${field.slotOffset * 8}); }`;
    case 'float32':
      return `get ${name}(): number { return this.reader.getFloat32(${field.slotOffset * 4}); }`;
    case 'float64':
      return `get ${name}(): number { return this.reader.getFloat64(${field.slotOffset * 8}); }`;
    case 'text':
      return `get ${name}(): string { return this.reader.getText(${field.slotOffset}); }`;
    case 'data':
      return `get ${name}(): Uint8Array { return this.reader.getData(${field.slotOffset}); }`;
    default:
      return `get ${name}(): unknown { return undefined; }`;
  }
}

/**
 * 获取字节偏移量
 */
function getByteOffset(field: FieldReader, typeKind: TypeKind): number {
  switch (typeKind) {
    case 'bool':
      return field.slotOffset * 8; // bit offset
    case 'int8':
    case 'uint8':
      return field.slotOffset;
    case 'int16':
    case 'uint16':
    case 'enum':
      return field.slotOffset * 2;
    case 'int32':
    case 'uint32':
    case 'float32':
      return field.slotOffset * 4;
    case 'int64':
    case 'uint64':
    case 'float64':
      return field.slotOffset * 8;
    default:
      return field.slotOffset;
  }
}

/**
 * 生成字段 setter
 */
function generateFieldSetter(field: FieldReader): string {
  const name = field.name;
  const type = field.slotType;
  const paramType = getTypeScriptTypeForSetter(type);
  const defaultValue = extractDefaultValue(field);
  
  if (!type) {
    return `set${capitalize(name)}(value: unknown): void { /* TODO */ }`;
  }
  
  // 如果有默认值，使用 XOR 编码
  if (defaultValue !== undefined && type.kind !== 'text' && type.kind !== 'data') {
    const encodedExpr = generateXorEncode('value', defaultValue, type.kind);
    const setterMethod = `set${capitalize(type.kind)}`;
    return `set${capitalize(name)}(value: ${paramType}): void { this.builder.${setterMethod}(${getByteOffset(field, type.kind)}, ${encodedExpr}); }`;
  }
  
  switch (type.kind) {
    case 'void':
      return `set${capitalize(name)}(value: void): void { /* void */ }`;
    case 'bool':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setBool(${field.slotOffset * 8}, value); }`;
    case 'int8':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt8(${field.slotOffset}, value); }`;
    case 'int16':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt16(${field.slotOffset * 2}, value); }`;
    case 'int32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt32(${field.slotOffset * 4}, value); }`;
    case 'int64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setInt64(${field.slotOffset * 8}, value); }`;
    case 'uint8':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint8(${field.slotOffset}, value); }`;
    case 'uint16':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint16(${field.slotOffset * 2}, value); }`;
    case 'uint32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint32(${field.slotOffset * 4}, value); }`;
    case 'uint64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setUint64(${field.slotOffset * 8}, value); }`;
    case 'float32':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat32(${field.slotOffset * 4}, value); }`;
    case 'float64':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setFloat64(${field.slotOffset * 8}, value); }`;
    case 'text':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setText(${field.slotOffset}, value); }`;
    case 'data':
      return `set${capitalize(name)}(value: ${paramType}): void { this.builder.setData(${field.slotOffset}, value); }`;
    default:
      return `set${capitalize(name)}(value: ${paramType}): void { /* TODO */ }`;
  }
}

/**
 * 获取 TypeScript setter 参数类型
 */
function getTypeScriptTypeForSetter(type: TypeReader | null): string {
  if (!type) return 'unknown';
  
  switch (type.kind) {
    case 'void': return 'void';
    case 'bool': return 'boolean';
    case 'int8':
    case 'int16':
    case 'int32':
    case 'uint8':
    case 'uint16':
    case 'uint32':
    case 'float32':
    case 'float64':
      return 'number';
    case 'int64':
    case 'uint64':
      return 'bigint';
    case 'text': return 'string';
    case 'data': return 'Uint8Array';
    default:
      return 'unknown';
  }
}

/**
 * 首字母大写
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * 生成 Enum 的 TypeScript 代码
 */
function generateEnum(node: NodeReader): string {
  const lines: string[] = [];
  const enumName = getShortName(node.displayName);
  
  lines.push(`export enum ${enumName} {`);
  for (const enumerant of node.enumEnumerants) {
    lines.push(`  ${enumerant.name} = ${enumerant.codeOrder},`);
  }
  lines.push('}');
  
  return lines.join('\n');
}

/**
 * 获取 TypeScript 类型字符串
 */
function getTypeScriptType(type: TypeReader | null, allNodes: NodeReader[]): string {
  if (!type) return 'unknown';
  
  switch (type.kind) {
    case 'void': return 'void';
    case 'bool': return 'boolean';
    case 'int8':
    case 'int16':
    case 'int32':
    case 'uint8':
    case 'uint16':
    case 'uint32':
    case 'float32':
    case 'float64':
      return 'number';
    case 'int64':
    case 'uint64':
      return 'bigint';
    case 'text': return 'string';
    case 'data': return 'Uint8Array';
    case 'list': {
      const elementType = type.listElementType;
      if (!elementType) return 'unknown[]';
      const elemTsType = getTypeScriptType(elementType, allNodes);
      return `${elemTsType}[]`;
    }
    case 'struct': {
      const structNode = allNodes.find(n => n.id === type.typeId);
      if (structNode) {
        return getShortName(structNode.displayName);
      }
      return 'unknown';
    }
    case 'enum': {
      const enumNode = allNodes.find(n => n.id === type.typeId);
      if (enumNode) {
        return getShortName(enumNode.displayName);
      }
      return 'unknown';
    }
    default:
      return 'unknown';
  }
}

/**
 * 从 displayName 获取短名称
 * 例如 "test-schema.capnp:Person" -> "Person"
 */
function getShortName(displayName: string): string {
  const colonIndex = displayName.lastIndexOf(':');
  if (colonIndex >= 0) {
    return displayName.substring(colonIndex + 1);
  }
  // 如果没有冒号，可能是文件名，返回空或文件名
  return displayName.replace(/\.capnp$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
}
