/**
 * Main code generator v2
 */

import { generateEnum } from './enum-gen.js';
import type { Schema } from './parser-v2.js';
import { generateStruct } from './struct-gen.js';

export interface GeneratorOptions {
  runtimeImportPath?: string;
}

const DEFAULT_OPTIONS: GeneratorOptions = {
  runtimeImportPath: '@naeemo/capnp',
};

export function generateCode(schema: Schema, options?: GeneratorOptions): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [];

  lines.push('// Generated by capnp-ts-codegen');
  lines.push('// DO NOT EDIT MANUALLY');
  lines.push('');
  lines.push(
    `import { MessageReader, MessageBuilder, StructReader, StructBuilder } from "${opts.runtimeImportPath}";`
  );
  lines.push('');

  for (const enum_ of schema.enums) {
    generateEnum(enum_, lines);
  }

  for (const struct of schema.structs) {
    generateStruct(struct, lines);
  }

  return lines.join('\n');
}
