/**
 * Cap'n Proto TypeScript 代码生成器
 */

import type { Field, Schema, StructDef } from './parser.js';

type EnumDef = Schema['enums'][number];

export function generateTypeScript(schema: Schema): string {
  const lines: string[] = [];

  // Header
  lines.push('// Generated by capnp-ts-codegen');
  lines.push(
    "import { StructReader, StructBuilder, MessageReader, MessageBuilder, ElementSize } from '@capnp-ts/core';"
  );
  lines.push('');

  // Enums
  for (const enumDef of schema.enums) {
    lines.push(generateEnum(enumDef));
    lines.push('');
  }

  // Structs
  for (const struct of schema.structs) {
    lines.push(generateStructReader(struct));
    lines.push('');
    lines.push(generateStructBuilder(struct));
    lines.push('');
  }

  return lines.join('\n');
}

function generateEnum(enumDef: EnumDef): string {
  const lines: string[] = [];
  lines.push(`export enum ${enumDef.name} {`);
  for (const { name, value } of enumDef.values) {
    lines.push(`  ${name} = ${value},`);
  }
  lines.push('}');
  return lines.join('\n');
}

function generateStructReader(struct: StructDef): string {
  const lines: string[] = [];
  lines.push(`export class ${struct.name}_Reader extends StructReader {`);

  for (const field of struct.fields) {
    const getter = generateFieldGetter(field);
    lines.push(getter);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateStructBuilder(struct: StructDef): string {
  const lines: string[] = [];
  lines.push(`export class ${struct.name}_Builder extends StructBuilder {`);

  for (const field of struct.fields) {
    const setter = generateFieldSetter(field);
    lines.push(setter);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateFieldGetter(field: Field): string {
  const type = mapCapnpTypeToTs(field.type);
  const method = getGetterMethod(field.type);

  if (field.isPointer) {
    return `
  get ${field.name}(): ${type} {
    return this.${method}(${field.offset});
  }`;
  }
  return `
  get ${field.name}(): ${type} {
    return this.${method}(${field.offset});
  }`;
}

function generateFieldSetter(field: Field): string {
  const type = mapCapnpTypeToTs(field.type);
  const method = getSetterMethod(field.type);

  if (field.isPointer) {
    return `
  set ${field.name}(value: ${type}) {
    this.${method}(${field.offset}, value);
  }`;
  }
  return `
  set ${field.name}(value: ${type}) {
    this.${method}(${field.offset}, value);
  }`;
}

function mapCapnpTypeToTs(capnpType: string): string {
  switch (capnpType) {
    case 'Bool':
      return 'boolean';
    case 'Int8':
    case 'Int16':
    case 'Int32':
    case 'UInt8':
    case 'UInt16':
    case 'UInt32':
    case 'Float32':
    case 'Float64':
      return 'number';
    case 'Int64':
    case 'UInt64':
      return 'bigint';
    case 'Text':
      return 'string';
    case 'Data':
      return 'Uint8Array';
    default:
      return 'unknown';
  }
}

function getGetterMethod(capnpType: string): string {
  switch (capnpType) {
    case 'Bool':
      return 'getBool';
    case 'Int8':
      return 'getInt8';
    case 'Int16':
      return 'getInt16';
    case 'Int32':
      return 'getInt32';
    case 'Int64':
      return 'getInt64';
    case 'UInt8':
      return 'getUint8';
    case 'UInt16':
      return 'getUint16';
    case 'UInt32':
      return 'getUint32';
    case 'UInt64':
      return 'getUint64';
    case 'Float32':
      return 'getFloat32';
    case 'Float64':
      return 'getFloat64';
    case 'Text':
      return 'getText';
    case 'Data':
      return 'getData';
    default:
      return 'getUnknown';
  }
}

function getSetterMethod(capnpType: string): string {
  switch (capnpType) {
    case 'Bool':
      return 'setBool';
    case 'Int8':
      return 'setInt8';
    case 'Int16':
      return 'setInt16';
    case 'Int32':
      return 'setInt32';
    case 'Int64':
      return 'setInt64';
    case 'UInt8':
      return 'setUint8';
    case 'UInt16':
      return 'setUint16';
    case 'UInt32':
      return 'setUint32';
    case 'UInt64':
      return 'setUint64';
    case 'Float32':
      return 'setFloat32';
    case 'Float64':
      return 'setFloat64';
    case 'Text':
      return 'setText';
    case 'Data':
      return 'setData';
    default:
      return 'setUnknown';
  }
}
